// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Simple Bank API
 *
 * API для работы с первым банком
 *
 * API version: 1.0.0
 */

package openapi




type UserPost201Response struct {

	// guid созданного пользователя
	Guid string `json:"guid,omitempty"`
}

// AssertUserPost201ResponseRequired checks if the required fields are not zero-ed
func AssertUserPost201ResponseRequired(obj UserPost201Response) error {
	return nil
}

// AssertUserPost201ResponseConstraints checks if the values respects the defined constraints
func AssertUserPost201ResponseConstraints(obj UserPost201Response) error {
	return nil
}
