// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Simple Bank API
 *
 * API для работы с первым банком
 *
 * API version: 1.0.0
 */

package openapi




type UserPostRequest struct {

	// Никнейм пользователя
	Username string `json:"username"`

	// Пароль пользователя
	Password string `json:"password"`

	// Почта пользователя
	Email string `json:"email"`
}

// AssertUserPostRequestRequired checks if the required fields are not zero-ed
func AssertUserPostRequestRequired(obj UserPostRequest) error {
	elements := map[string]interface{}{
		"username": obj.Username,
		"password": obj.Password,
		"email": obj.Email,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertUserPostRequestConstraints checks if the values respects the defined constraints
func AssertUserPostRequestConstraints(obj UserPostRequest) error {
	return nil
}
